# **Linear Combination**

### You will work with a simple data set that contains factory production values of electrical machinery parts for a corporation. you will perform the following tasks:
- Load and study the data
- Extract production values as vectors from the data
- Extract number of working days as scalars from the data
- Use scalar multiplication to scale production values by number of working days
- Code a linear combination of vectors using addition and scalar multiplication

## Task 1 - Load and study the data

In [5]:
# Load "numpy" and "pandas" for manipulating numbers, vectors and data frames
import numpy as np
import pandas as pd

In [17]:
# Read in the "Factory_Production.csv" file as a Pandas Data Frame
# Note: Make sure the code and the data are in the same folder or specify the appropriate path for the data
df=df.set_index("Factory")
df = pd.read_csv("//content//sample_data//factory_data_indexed.csv")

In [18]:
# Take a brief look at the data frame using ".head()"

df.head()

  Factory  Generators  Motors  Cables  Days
0       A           8      17     232   352
1       B           6      20     203   348
2       C          10      16     187   337
3       D           7      24     218   357
4       E          13      13     256   362

##### Feature Description:
This data set contains the production values of power units such as generators, motors and cables of different factories belonging to the same corporation.
- Factory = unique label assigned to a factory unit for the purpose of identification
- Generators = number of generators produced by the factory in a day
- Motors = number of motors produced by the factory in a day
- Cables = number of cables produced by the factory in a day
- Days = number of working days of the factory in a year

##### study its features such as:
- The number of factory units
- The number of machine parts
- The ranges of production values

In [19]:
# Check the dimensions of the data frame using ".shape"

df.shape

(10, 5)

In [20]:
# View basic information about the data frame using ".info()"
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Factory     10 non-null     object
 1   Generators  10 non-null     int64
 2   Motors      10 non-null     int64
 3   Cables      10 non-null     int64
 4   Days        10 non-null     int64
dtypes: int64(4), object(1)
memory usage: 532.0+ bytes

In [22]:
# View a statistical summary of the data frame using ".describe()"
# Note: Use ".transpose()" to make the summary easier to read

df.describe()

       Generators     Motors      Cables        Days
count   10.000000  10.000000   10.000000   10.000000
mean     8.900000  17.800000  217.100000  349.600000
std      2.601282   3.521363   21.377298    8.983936
min      5.000000  13.000000  187.000000  337.000000
25%      7.250000  15.250000  203.500000  342.750000
50%      8.500000  17.500000  214.000000  350.000000
75%     10.750000  19.750000  230.250000  356.500000
max     13.000000  24.000000  256.000000  362.000000

#### Observations

- There are 10 rows and 4 columns
- The first 3 columns contain the production values of generators, motors and cables
- The fourth column contains the number of working days of the factories

## Task 2 - Extract production values as vectors from the data


- The factory production values for each factory are contained in the "Generators", "Motors" and "Cables" features.
- Separating these features from the "Days" feature could be useful.

In [23]:
# Drop the "Days" column from the data frame using ".drop()" and save the data in a new data frame called "df_prod"
df_prod = df.drop("Days", axis=1)

In [24]:
# Take a brief look at the data frame "df_prod" using ".head()"

df_prod.head()

  Factory  Generators  Motors  Cables
0       A           8      17     232
1       B           6      20     203
2       C          10      16     187
3       D           7      24     218
4       E          13      13     256

In [31]:
# Access the vector of production values for factory "D" using ".loc[]" from the data frame "df_prod"
df_prod.loc[3]

Factory         D
Generators      7
Motors         24
Cables        218
Name: 3, dtype: object

In [32]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#### Observations

- The vector of production values for any factory is 3-long
- These vectors contain the production values of generators, motors and cables per day

## Task 3 - Extract number of working days as scalars from the data



- The number of working days for each factory is stored in the "Days" column of the data frame "df".
- These will be the scalars that we will use to multiply with the production value vectors.

In [33]:
# Access the "Days" column from the data frame "df"

df.loc[:,'Days']

0    352
1    348
2    337
3    357
4    362
5    345
6    338
7    355
8    360
9    342
Name: Days, dtype: int64

In [35]:
# Access the number of working days of factory "G" from the Pandas Series obtained by accessing the "Days" column
# Note: You may use ".loc[]" to access these values as well
df.loc[6,'Days']

np.int64(338)

#### Observations

- The "Days" column contains the number of working days in a year of each factory.
- These will be the scalars that we will use to multiply with the production value vectors.

## Task 4 - Use scalar multiplication to scale production values by number of working days

- The production values for each factory are available in the data frame "df_prod".
- The number of working days in a year for each factory can be extracted from the data frame "df".
- The product of the vector of production values and the number of working days is a scaled version of the original vector.

![](https://miro.medium.com/max/1400/1*gf3HdrkDBi6Dch_XxVuYvA.png)

## **`Watch Video 5 : Matrix Multiplication`**

In [36]:
# Access the vector of production values for factory "B" using ".loc[]" from the data frame "df_prod"

df_prod.loc[1]

Factory         B
Generators      6
Motors         20
Cables        203
Name: 1, dtype: object

In [37]:
# Access the number of working days of factory "B"

df.loc[1,'Days']

np.int64(348)

In [38]:
# Multiply the vector of production values for factory "B" by its number of working days

df_prod.loc[1]*df.loc[1,'Days']

Factory       BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB...
Generators                                                 2088
Motors                                                     6960
Cables                                                    70644
Name: 1, dtype: object

#### Observations

- The product of the vector of production values and the number of working days is a scaled version of the original vector.
- The scaled vector of production values for a certain factory shows the number of machine parts produced in a full year.

## Task 5 - Code a linear combination of vectors using addition and scalar multiplication

- The vector of daily production values for a certain factory can be accessed from the data frame "df_prod".
- The number of working days in a year for each factory can be extracted from the data frame "df".
- The total production of a certain factory in a full year can be obtained using scalar multiplication.

![](https://www2.seas.gwu.edu/~simhaweb/lin/modules/module3/figures/matrixvec2.png)

In [42]:
import numpy as np

# Calculate the total production values of all the factories using their production value vectors and number of working days
# Add these vectors to obtain a single vector that contains the yearly production values of the whole corporation
# Note: Create a Numpy List called "total" with a size of 3 and fill it with zeroes
# Note: You may use the "total" list to cumulatively add the yearly production values for each factory

total = np.array([0,0,0]) # Initialize total as a NumPy array of zeros of size 3

for factory_index in df.index:
    # Select only the numeric production columns for the current factory
    production_vector = df_prod.loc[factory_index, ['Generators', 'Motors', 'Cables']]

    # Get the number of working days for the current factory
    working_days = df['Days'][factory_index]

    # Perform scalar multiplication and add to total
    total = total + working_days * production_vector

In [43]:
# Print the "total" series
print(total)

Generators     31133
Motors         62238
Cables        760570
dtype: object

#### Observations

- The corporation produces 30355 generators in a year.
- The corporation produces 56602 motors in a year.
- The corporation produces 708048 cables in a year.

#### Conclusions

- From the factory production data, we can calculate the total production of the corporation
- We can treat the production values of each factory as vectors
- We can use the number of days as scalars to scale each factory's production values.
- We can use a linear combination of number of working days and production values to calculate the total production.

# **FEEDBACK**

https://forms.zohopublic.in/cloudyml/form/CloudyMLStatisticsFeedbackForm/formperma/WV946wnf0sDM_tOlH87RxZR9yMceKWGrtuPOyXzzCRc