# **Norm of Vector**

![](https://mathsimulationtechnology.files.wordpress.com/2012/02/la_r2vector_length.jpg?w=298&h=285)

### You will work with a simple data set that contains the sales in a particular year of various sanitizers. you will perform the following tasks:

- Load and study the data
- Extract vectors from the data
- Calculate norms of vectors
- Print a sorted list of store IDs in terms of their sales of sanitizers
- Print a sorted list of sanitizers in terms of their popularity
- Create a function to calculate the norm of the difference of two vectors
- Create a function that returns the ID of the store with the most similar sales as a given store
- Create a function that returns the name of a sanitizer with the most similar sales as a given sanitizer

# **`WATCH ALL VIDEOS IN THE PORTAL`**
## **`Watch Video 3 : Norm Theory`**

## Task 1 - Load and study the data

In [1]:
# Load "numpy" and "pandas" for manipulating numbers, vectors and data frames
import pandas as pd
import numpy as np

In [2]:
# Read in the "Store_Sanitizer_Sales.csv" file as a Pandas Data Frame
# Note: Make sure the code and the data are in the same folder or specify the appropriate path for the data
data = {
    "Store ID": [
        "AMD463","BGL198","CXF008","DRH187","EWO651",
        "FLJ843","GKM230","HRT117","IDT818","JRB076",
        "KTG143","LXM794","MRN637","NGP835","OEP108"
    ],
    "Dettol":   [8.4, 7.3, 9.2,11.5, 7.4, 8.9, 6.8,10.2, 7.7, 9.5, 8.1, 9.8, 7.2, 8.6, 9.0],
    "Savlon":   [6.5, 8.1,10.2, 7.1, 6.9, 7.5, 9.3, 8.8, 7.0, 6.6, 8.4, 9.1, 7.3, 8.0, 7.8],
    "Himalaya": [9.8,10.5, 8.6, 8.9,10.0, 9.4, 8.7, 9.9,10.2, 8.5, 9.7,10.1, 8.8, 9.3, 9.6],
    "Lifebuoy": [5.8, 9.1,10.0, 8.4, 5.8, 7.2, 8.5, 9.0, 6.3, 7.9, 8.6, 9.4, 7.1, 8.8, 8.2],
    "Kaya":     [3.2, 4.1, 4.2, 5.0, 3.7, 4.5, 3.9, 4.8, 3.6, 4.3, 4.9, 5.1, 3.8, 4.6, 4.7],
    "Godrej":   [7.1, 3.8, 5.6, 6.1, 8.2, 7.4, 6.9, 5.5, 7.8, 6.3, 7.0, 5.9, 6.7, 7.6, 6.5],
    "Dabur":    [3.5, 4.0, 2.8, 4.6, 4.5, 3.9, 4.2, 3.7, 4.1, 3.6, 4.3, 4.7, 3.8, 4.4, 4.0]
}

df = pd.DataFrame(data)
print(df)

   Store ID  Dettol  Savlon  Himalaya  Lifebuoy  Kaya  Godrej  Dabur
0    AMD463     8.4     6.5       9.8       5.8   3.2     7.1    3.5
1    BGL198     7.3     8.1      10.5       9.1   4.1     3.8    4.0
2    CXF008     9.2    10.2       8.6      10.0   4.2     5.6    2.8
3    DRH187    11.5     7.1       8.9       8.4   5.0     6.1    4.6
4    EWO651     7.4     6.9      10.0       5.8   3.7     8.2    4.5
5    FLJ843     8.9     7.5       9.4       7.2   4.5     7.4    3.9
6    GKM230     6.8     9.3       8.7       8.5   3.9     6.9    4.2
7    HRT117    10.2     8.8       9.9       9.0   4.8     5.5    3.7
8    IDT818     7.7     7.0      10.2       6.3   3.6     7.8    4.1
9    JRB076     9.5     6.6       8.5       7.9   4.3     6.3    3.6
10   KTG143     8.1     8.4       9.7       8.6   4.9     7.0    4.3
11   LXM794     9.8     9.1      10.1       9.4   5.1     5.9    4.7
12   MRN637     7.2     7.3       8.8       7.1   3.8     6.7    3.8
13   NGP835     8.6     8.0       9.3       8.8   4.6     7.6    4.4
14   OEP108     9.0     7.8       9.6       8.2   4.7     6.5    4.0

In [3]:
# Take a brief look at the data frame using ".head()"
df.head()

  Store ID  Dettol  Savlon  Himalaya  Lifebuoy  Kaya  Godrej  Dabur
0   AMD463     8.4     6.5       9.8       5.8   3.2     7.1    3.5
1   BGL198     7.3     8.1      10.5       9.1   4.1     3.8    4.0
2   CXF008     9.2    10.2       8.6      10.0   4.2     5.6    2.8
3   DRH187    11.5     7.1       8.9       8.4   5.0     6.1    4.6
4   EWO651     7.4     6.9      10.0       5.8   3.7     8.2    4.5

#### Feature Description:
- The data set contains sales values of sanitizers in various stores.
- The sales values are in millions of units sold in the previous year.
- Each row contains the sales values of all the sanitizers for a particular store.
- Each column contains the sales values of a particular sanitizer in all the stores.

#### study its features such as:
- The number of stores
- The number of sanitizers
- The ranges of sales

In [4]:
# Check the dimensions of the data frame using ".shape"

df.shape

(15, 8)

In [5]:
# View basic information about the data frame using ".info()"

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Store ID  15 non-null     object
 1   Dettol    15 non-null     float64
 2   Savlon    15 non-null     float64
 3   Himalaya  15 non-null     float64
 4   Lifebuoy  15 non-null     float64
 5   Kaya      15 non-null     float64
 6   Godrej    15 non-null     float64
 7   Dabur     15 non-null     float64
dtypes: float64(7), object(1)
memory usage: 1.1+ KB

In [6]:
# View a statistical summary of the data frame using ".describe()"
# Note: Use ".transpose()" to make the summary easier to read

df.describe()

,Dettol,Savlon,Himalaya,Lifebuoy,Kaya,Godrej,Dabur
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,8.640000,7.906667,9.466667,8.006667,4.293333,6.560000,4.006667
std,1.288299,1.083293,0.639940,1.299707,0.570046,1.102465,0.492032
min,6.800000,6.500000,8.500000,5.800000,3.200000,3.800000,2.800000
25%,7.550000,7.050000,8.850000,7.150000,3.850000,6.000000,3.750000
50%,8.600000,7.800000,9.600000,8.400000,4.300000,6.700000,4.000000
75%,9.350000,8.600000,9.950000,8.900000,4.750000,7.250000,4.350000
max,11.500000,10.200000,10.500000,10.000000,5.100000,8.200000,4.700000

#### Observations

- There are 15 rows and 7 columns in the data
- Each row corresponds to the sales values of different sanitizers of a particular store
- Each column corresponds to the sales values of a particular sanitizer in different stores
- The sales values range from 1.6 to 16.3 million units

## Task 2 - Extract vectors from the data

- You have seen that there are two types of vectors that we can extract from the data:
- Row vectors - these contain the sales values of different sanitizers of a particular store
- Column vectors - these contain the sales values of a particular sanitizer in different stores

In [7]:
df.loc[df['Store ID'] == "DRH187"]

  Store ID  Dettol  Savlon  Himalaya  Lifebuoy  Kaya  Godrej  Dabur
3   DRH187    11.5     7.1       8.9       8.4   5.0     6.1    4.6

In [8]:
# Access the row vector for the store with ID "LXM794" using ".loc[]"
df.loc[df['Store ID']=='LXM794']

   Store ID  Dettol  Savlon  Himalaya  Lifebuoy  Kaya  Godrej  Dabur
11   LXM794     9.8     9.1      10.1       9.4   5.1     5.9    4.7

In [9]:
# Access the column vector for the sanitizer "Dettol"
# Note: You may access column vectors either directly or using ".loc[]"

df.loc[:,['Dettol']]

    Dettol
0      8.4
1      7.3
2      9.2
3     11.5
4      7.4
5      8.9
6      6.8
7     10.2
8      7.7
9      9.5
10     8.1
11     9.8
12     7.2
13     8.6
14     9.0

In [10]:
# Access the column vector for the sanitizer "Kaya"

df.loc[:,['Kaya']]

    Kaya
0    3.2
1    4.1
2    4.2
3    5.0
4    3.7
5    4.5
6    3.9
7    4.8
8    3.6
9    4.3
10   4.9
11   5.1
12   3.8
13   4.6
14   4.7

#### Observations

- There are two types of vectors that we can work with:
- The sales values of different sanitizers of a particular store (row vectors)
- Note: These are 7-long since there are 7 sanitizers in the data set
- The sales values of a particular sanitizer in different stores (column vectors)
- Note: These are 15-long since there are 15 stores in the data set

## Task 3 - Calculate norms of vectors

- To perform the tasks in this exercise, we will use metrics that are derived from norms of vectors
- So, let's get comfortable with calculating norms using Numpy

## **`Watch Video 4 : Norm(Coding)`**

In [11]:
# Calculate the norm of the row vector for the store with ID "GKM230" using "np.linalg.norm()"
# Note: Leave all parameters as default except the input vector

np.linalg.norm(df.loc[df['Store ID'] == 'GKM230'].drop(columns=['Store ID']).values[0])

np.float64(19.003420744697518)

In [12]:
# Calculate the L2 norm of the row vector for the store with ID "GKM230" using "np.linalg.norm()"
# Note: This time, specify "ord = 2" as one of the parameters

np.linalg.norm(df.loc[df['Store ID'] == 'GKM230'].drop(columns=['Store ID']).values[0], ord=2)

np.float64(19.003420744697518)

##### Note: The default norm calculated by "np.linalg.norm()" is the L2 norm, that is the "ord" parameter is set to 2 by default

![](https://miro.medium.com/max/1056/1*r6RXOl5FoSbY6urC9HjUcw.png)

In [13]:
# Calculate the L1 norm of the row vector for the store with ID "GKM230" using "np.linalg.norm()"
# Note: This time, specify "ord = 1" as one of the parameters
np.linalg.norm(df.loc[df['Store ID'] == 'GKM230'].drop(columns=['Store ID']).values[0], ord=1)

np.float64(48.3)

In [14]:
# Calculate the L3 norm of the row vector for the store with ID "GKM230" using "np.linalg.norm()"
# Note: This time, specify "ord = 3" as one of the parameters

np.linalg.norm(df.loc[df['Store ID'] == 'GKM230'].drop(columns=['Store ID']).values[0], ord=3)

np.float64(14.183524169435495)

In [15]:
# Calculate the max norm of the row vector for the store with ID "GKM230" using "np.linalg.norm()"
# Note: This time, specify "ord = np.inf" as one of the parameters
np.linalg.norm(df.loc[df['Store ID'] == 'GKM230'].drop(columns=['Store ID']).values[0], ord=np.inf)

np.float64(9.3)

##### Note: For the remainder of this exercise, we will use the default (L2) norm for the sake of simplicity and consistency

In [16]:
# Calculate the norm of the row vector for the store with ID "KTG143" using "np.linalg.norm()"
np.linalg.norm(df.loc[df['Store ID'] == 'KTG143'].drop(columns=['Store ID']).values[0], ord=2)

np.float64(19.892712233378333)

In [17]:
# Calculate the norm of the row vector for the store with ID "OEP108" using "np.linalg.norm()"

np.linalg.norm(df.loc[df['Store ID'] == 'OEP108'].drop(columns=['Store ID']).values[0], ord=2)

np.float64(19.534072796014662)

In [18]:
# Calculate the norm of the column vector for the sanitizer "Himalaya" using "np.linalg.norm()"
np.linalg.norm(df['Himalaya'], ord=2)

np.float64(36.742346141747674)

In [19]:
# Calculate the norm of the column vector for the sanitizer "Dabur" using "np.linalg.norm()"
np.linalg.norm(df['Dabur'], ord=2)

np.float64(15.626579920123278)

#### Observations

- Norms can be calculated using different orders ranging from 1, 2, 3, ... up to infinity
- The default norm is the L2 norm, which is also the Euclidean distance, and hence equal to the magnitude of the vector
- The magnitude of a vector (L2 norm) can be used as a measure of the strength of the values in that vector
- The smaller the norm of a vector, the weaker the vector, and vice versa
- The larger the norm of a vector, the stronger the vector, and vice versa

## Task 4 - Print a sorted list of store IDs in terms of their sales of sanitizers

- The norm of a vector indicates the strength of the values in that vector
- The smaller the norm of a vector, the weaker the vector, and vice versa
- The larger the norm of a vector, the stronger the vector, and vice versa
- We can use the norms of row vectors as a measure of the overall sales value of different stores

In [35]:
stores = pd.Series(index=df['Store ID'],dtype='float64') # create series with 'Store ID' as index

for idx in df.index:
    # Select the current row by its integer index
    current_row = df.loc[idx]
    # Drop the 'Store ID' column to get only numerical sales data
    numerical_sales = current_row.drop('Store ID').values
    # Calculate the norm of the numerical sales data
    norm_value = np.linalg.norm(numerical_sales)
    # Assign the norm to the 'stores' Series using the actual 'Store ID' as the label
    store_id_label = current_row['Store ID']
    stores.loc[store_id_label] = norm_value

stores = stores.sort_values(ascending=False)# sort by values

In [36]:
# Print the "stores" series
print(stores)

Store ID
LXM794    21.263349
HRT117    20.675348
CXF008    20.481211
DRH187    20.391175
NGP835    20.004250
KTG143    19.892712
OEP108    19.534073
FLJ843    19.127990
GKM230    19.003421
BGL198    18.952836
IDT818    18.510267
JRB076    18.428511
EWO651    18.362734
AMD463    17.759223
MRN637    17.514280
dtype: float64

#### Observations

- The store with ID "KTG143" has the highest sales
- The user with ID "LXM794" has the lowest sales

## Task 5 - Print a sorted list of sanitizers in terms of their popularity

- The norm of a vector indicates the strength of the values in that vector
- The smaller the norm of a vector, the weaker the vector, and vice versa
- The larger the norm of a vector, the stronger the vector, and vice versa
- We can use the norms of column vectors as a measure of the overall sales of different sanitizers

In [39]:
# Calculate the norms of the column vectors for all 7 sanitizers and sort them in descending order
# Note: Use these norms as a measure of overall sales values of the different sanitizers
# Note: Store the resulting values in a Pandas Series with index as sanitizer names and name the series "sanitizers"
# Note: The "index" parameter of the series can be set as "df.columns"
# Note: You may need to specify the "dtype" parameter of the series as "float64" to avoid some warnings
# Note: Use the ".sort_values()" function with the "ascending" parameter set to "False"

sanitizers = pd.Series(index=df.columns[1:], dtype='float64') # create series, excluding 'Store ID'

for sanitizer in sanitizers.index:
    sanitizers.loc[sanitizer] = np.linalg.norm(df[sanitizer])# norm of sanitizer

sanitizers = sanitizers.sort_values(ascending=False) # sort by values

In [40]:
# Print the "sanitizers" series

print(sanitizers)

Himalaya    36.742346
Dettol      33.807987
Lifebuoy    31.388692
Savlon      30.889480
Godrej      25.739464
Kaya        16.764248
Dabur       15.626580
dtype: float64

#### Observations

- The most popular sanitizer is "Himalaya"
- The least popular sanitizer is "Kaya"

## Task 6 - Create a function to calculate the norm of the difference of two vectors


- The norm of the difference between two vectors can be used as a similarity measure between those two vectors
- The smaller the norm of the difference vector, the more similar the two original vectors, and vice versa
- The larger the norm of the difference vector, the more dissimilar the two original vectors, and vice versa

In [41]:
# Create a function called "sim()" which takes in two vectors and returns similarity score between them
# Note: Use the "np.linalg.norm()" method on the difference of the two vectors to calculate their similarity
# Note: The order in which the vectors are subtracted does not matter

def sim(vec1, vec2):
  return(np.linalg.norm(vec1-vec2))
    # code here

In [46]:
# Calculate the similarity between the sales of the stores with IDs "AMD463" and "HRT117" using the function "sim()"
sim(df.loc[df['Store ID'] == 'AMD463'], df.loc[df['Store ID'] == 'HRT117'])

np.float64(nan)

In [47]:
# Calculate the similarity between the sales of the stores with IDs "NGP835" and "GKM230" using the function "sim()"
sim(df.loc[df['Store ID'] == 'NGP835'], df.loc[df['Store ID'] == 'GKM230'])

np.float64(nan)

In [48]:
# Calculate the similarity between the sales of the sanitizers "Lifebuoy" and "Himalaya" using the function "sim()"
sim(df['Lifebuoy'], df['Himalaya'])

np.float64(8.116033513977133)

In [49]:
# Calculate the similarity between the sales of the sanitizers "Dettol" and "Godrej" using the function "sim()"
sim(df['Dettol'], df['Godrej'])

np.float64(10.734057946554975)

In [51]:
# Calculate the similarity between the sales of the store with ID "JRB076" and itself using the function "sim()"
sim(df.loc[df['Store ID'] == 'JRB076'].drop(columns=['Store ID']), df.loc[df['Store ID'] == 'JRB076'].drop(columns=['Store ID']))

np.float64(0.0)

#### Observations

- The norm of the difference between two vectors can be used as a similarity measure between those two vectors
- The norm of the difference between a vector and itself is 0
- The smaller the norm of the difference between two vectors, the higher their similarity score, and vice versa
- The larger the norm of the difference between two vectors, the lower their similarity score, and vice versa

## Task 7 - Create a function that returns the ID of the store with the most similar sales as a given store

- The norm of the difference between two vectors can be used as a similarity measure between those two vectors
- The smaller the norm of the difference between two vectors, the higher their similarity score, and vice versa
- The larger the norm of the difference between two vectors, the lower their similarity score, and vice versa
- We will create a function that returns the ID of the store with the most similar sales as a given store

![](https://datascience-enthusiast.com/figures/cosine_sim.png)

In [62]:
# Define a function "storesim()" that takes in the ID of a store and returns the ID of the store with the most similar sales
# Note: Use the "sim()" function to measure similarities between stores (using their row vectors)
# Note: You may create a temporary Pandas Series within the "storesim()" function to store the similarity values
# Note: The "index" parameter of the series can be set as "df.index"
# Note: You may need to specify the "dtype" parameter of the series as "float64" to avoid some warnings
# Note: You may sort the entries in this series and return the second index entry
# Note: Use the ".sort_values()" function with the default value for the "ascending" parameter, which is "True"
# Note: The first entry after sorting will be trivial

def storesim(store1_id):
  # Initialize the series to store similarity scores with the actual 'Store ID's as index
  similarity_scores = pd.Series(index=df['Store ID'], dtype='float64')

  # Extract the sales vector for the reference store (store1_id)
  # Filter the DataFrame to get the row for store1_id, drop the 'Store ID' column, and get the first (and only) row as a Series.
  vec1_data = df[df['Store ID'] == store1_id].drop(columns=['Store ID']).iloc[0]

  # Iterate through all stores to calculate similarity
  for idx in df.index:
    current_store_id_in_loop = df.loc[idx, 'Store ID']

    # Extract the sales vector for the current store in the loop
    # Get the row by integer index, then drop the 'Store ID' column to get only numerical data.
    vec2_data = df.loc[idx].drop('Store ID')

    # Calculate similarity using the 'sim' function
    similarity_scores.loc[current_store_id_in_loop] = sim(vec1_data, vec2_data)

  # Sort the similarity scores in ascending order (smaller difference means higher similarity)
  # The first entry will be the store itself (similarity 0), the second will be the most similar different store.
  return similarity_scores.sort_values(ascending=True).index[1]

In [63]:
# Use the function "storesim()" to find the ID of the store whose sales are most similar to the store with ID "AMD463"
storesim('AMD463')

'IDT818'

In [64]:
# Use the function "storesim()" to find the ID of the store whose sales are most similar to the store with ID "NGP835"
storesim('NGP835')

'KTG143'

In [65]:
# Use the function "storesim()" to find the ID of the store whose sales are most similar to the store with ID "CXF008"
storesim('CXF008')

'HRT117'

In [66]:
# Use the function "storesim()" to find the ID of the store whose sales are most similar to the store with ID "BGL198"
storesim('BGL198')

'OEP108'

#### Observations

- The norm of the difference between row vectors is a measure of similarity between the sales in different stores
- The similarity score is not symmetric
- Rather it pertains to a specific case (such as a specific store)
- This is because it is possible for X to be most similar to Y and Y to be most similar to Z
- This happens when X and Z are not as similar to each other as X and Y or Y and Z
- Transitivity, on the other hand, is a useful assumption for further analysis

## Task 8 - Create a function that returns the name of a sanitizer with the most similar sales as a given sanitizer

- The norm of the difference between two vectors can be used as a similarity measure between those two vectors
- The smaller the norm of the difference between two vectors, the higher their similarity score, and vice versa
- The larger the norm of the difference between two vectors, the lower their similarity score, and vice versa
- We will create a function that returns the name of the sanitizer whose sales are most similar to a given sanitizer

In [82]:
# Define a function "sanisim()" that takes in the name of a sanitizer and returns sanitizer name with the most similar sales
# Note: Use the "sim()" function to measure similarities between sanitizers (using their column vectors)
# Note: You may create a temporary Pandas Series within the "sanisim()" function to store the similarity values
# Note: The "index" parameter of the series can be set as "df.columns"
# Note: You may need to specify the "dtype" parameter of the series as "float64" to avoid some warnings
# Note: You may sort the entries in this series and return the second index entry
# Note: Use the ".sort_values()" function with the default value for the "ascending" parameter, which is "True"
# Note: The first entry after sorting will be trivial

def sanisim(sani1):
    similarity_scores = pd.Series(index=df.columns[1:], dtype='float64')
    for sanitizer in similarity_scores.index:
        similarity_scores.loc[sanitizer] = sim(df[sani1], df[sanitizer])

    return (similarity_scores.sort_values(ascending=True).index[1])

In [83]:
# Use the function "sanisim()" to find the name of the sanitizer whose sales are most similar to the sanitizer "Godrej"
sanisim('Godrej')

'Savlon'

In [84]:
# Use the function "sanisim()" to find the name of the sanitizer whose sales are most similar to the sanitizer "Dabur"
sanisim('Dabur')

'Kaya'

In [85]:
# Use the function "sanisim()" to find the name of the sanitizer whose sales are most similar to the sanitizer "Himalaya"
sanisim('Himalaya')

'Dettol'

In [86]:
# Use the function "sanisim()" to find the name of the sanitizer whose sales are most similar to the sanitizer "Dettol"
sanisim('Dettol')

'Lifebuoy'

#### Observations

- The norm of the difference between column vectors is a measure of similarity between the sales of different sanitizers
- The similarity score is not symmetric
- Rather it pertains to a specific case (such as a specific sanitizer)
- This is because it is possible for X to be most similar to Y and Y to be most similar to Z
- This happens when X and Z are not as similar to each other as X and Y or Y and Z
- Transitivity, on the other hand, is a useful assumption for further analysis

#### Conclusions

- From the sales data, we can extract row vectors (sales of a store) and column vectors (sales of a sanitizer)
- We can use norms of row vectors for particular stores to measure their overall sales
- We can use norms of column vectors for particular sanitizers to measure their popularity
- We can use the norm of the difference between row vectors of two stores to measure the similarity in their sales
- We can use the norm of the difference between column vectors of two sanitizers to measure the similarity
- Using these measures, we can recommend decisions to certain stores about which sanitizers to sell more of and less of
- This is a very basic look into the working methodology of sales similarity analysis

# **FEEDBACK**

https://forms.zohopublic.in/cloudyml/form/CloudyMLStatisticsFeedbackForm/formperma/WV946wnf0sDM_tOlH87RxZR9yMceKWGrtuPOyXzzCRc